import { Metadata } from "next";
import { FC } from "react";

interface SignInPageProps {}

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const SignInPage: FC<SignInPageProps> = ({}) => {
  return (
    <div>
      <h1>SignInPage</h1>
    </div>
  );
};

export default SignInPage;
